Update faust2caqt for QT6
Without this change faust2caqt fails due to the usage of std::filesystem in QT6, with errors such as:

```/opt/homebrew/lib/QtCore.framework/Headers/qfileinfo.h:120:14: error: '~path' is unavailable: introduced in macOS 10.15
    { return QtPrivate::toFilesystemPath(absoluteFilePath()); }```

if supporting macOS < 10.15 is important, then this might not be the best fix